name: docker_build
on:
  push: # push 到主分支自动 发布
    branches: ["docker"]
    paths-ignore: # 忽略一些不必要的文件
      - ".gitignore"
      - "README.md"
      - ".github/**"
      - "00.static"
      - "04.update"
  pull_request:
    branches: ["docker"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4       
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
      #导入这个模块来完成自动编译和推送
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          #在这里通过加入需要编译的平台和前面配好的QEMU，buildx来达到多平台编译
          platforms: linux/amd64,linux/arm64,linux/arm/V7,linux/arm/V8
          tags: xuewuerduo/svnadmin2:latest
      - name: Update repo description
        uses: peter-evans/DOCKER-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xuewuerduo/SvnAdminV2.0
          short_description: '本镜像仅对witersen大佬的SvnAdminV2.0项目进行自动化docker镜像打包，自动构建生成amd64、arm64、arm/v7、arm/v8版本镜像，作为对大佬仓库的补充，对于大佬的代码无改动,再次感谢大佬的付出'
          readme_file: 'README.md'
